on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Flatpak
permissions:
  id-token: write
  contents: read
jobs:
  gnome-flatpak:
    name: "GNOME on Flatpak"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: org.nickvision.cavalier.gnome.flatpak
          manifest-path: flatpak/org.nickvision.cavalier.gnome.json
          cache-key: flatpak-builder-gnome-${{ github.sha }}
          arch: ${{ matrix.arch }}
          restore-cache: true
  qt-flatpak:
    name: "QT on Flatpak"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: org.nickvision.cavalier.qt.flatpak
          manifest-path: flatpak/org.nickvision.cavalier.qt.json
          cache-key: flatpak-builder-qt-${{ github.sha }}
          arch: ${{ matrix.arch }}
          restore-cache: true
