on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  id-token: write
  contents: read
env:
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: "Build on x64"
    runs-on: windows-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Environment"
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          mkdir build
          Invoke-WebRequest https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.21-v1.16/gettext0.21-iconv1.16-shared-64.zip -OutFile gettext.zip
          Expand-Archive -Force 'gettext.zip'
          move gettext\bin\* C:\Windows\System32
          choco install innosetup
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: libnick qtbase qtsvg qttools
          triplet: x64-windows
          revision: cf035d9916a0a23042b41fcae7ee0386d245af08
          token: ${{ secrets.GITHUB_TOKEN }}
          github-binarycache: true
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -G "Visual Studio 17 2022" ..
          cmake --build . --config Release
      - name: "Create Installer"
        working-directory: ${{github.workspace}}/inno
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest https://aka.ms/vs/17/release/vc_redist.x64.exe -OutFile vc_redist.x64.exe
          Invoke-WebRequest https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe -OutFile vc_redist.2012.x64.exe
          Invoke-WebRequest https://github.com/karlstav/cava/releases/download/0.10.3/cava_win.zip -OutFile cava.zip
          Expand-Archive -Force 'cava.zip'
          Remove-Item -Force cava\config
          iscc setup.iss
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/inno/NickvisionCavalierSetup.exe
          name: Windows-x64-Release
